// Code generated by hertz generator. DO NOT EDIT.

package routers

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	//router "tiktok-gateway/internal/routers/router"
)

// register registers all routers.
func Register(r *server.Hertz) {

	GeneratedRegister(r)

	customizedRegister(r)
}
