// Code generated by hertz generator.

package routers

import (
	"context"

	"github.com/41197-yhkt/tiktok/gateway/internal/chat"
	"github.com/41197-yhkt/tiktok/gateway/internal/handler"
	"github.com/41197-yhkt/tiktok/gateway/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	group := r.Group("/douyin")
	group.POST("/user/register", handler.DouyinUserRegisterMethod, middleware.JwtMiddleware.LoginHandler)
	group.POST("/user/login", middleware.JwtMiddleware.LoginHandler)
	auth := group.Group("/user", middleware.JwtMiddleware.MiddlewareFunc())
	auth.GET("/", handler.DouyinUserMethod)
	auth = group.Group("/relation", middleware.JwtMiddleware.MiddlewareFunc())
	auth.POST("/action", handler.DouyinRelationActionMethod)
	auth.GET("/follow/list", handler.DouyinRelationFollowListMethod)
	auth.GET("/follower/list", handler.DouyinRelationFollowerListMethod)
	auth.GET("/friend/list", handler.DouyinRelationFriendListMethod)

	// feed不需jwt
	group.GET("/feed", handler.DouyinFeedMethod)
	group.GET("/ws", func(c context.Context, ctx *app.RequestContext) {
		chat.ServeWs(ctx, chat.ChatHub)
	})

	auth2 := group.Group("/publish", middleware.JwtMiddleware.MiddlewareFunc())
	auth3 := group.Group("/favorite", middleware.JwtMiddleware.MiddlewareFunc())
	auth4 := group.Group("/comment", middleware.JwtMiddleware.MiddlewareFunc())

	auth2.POST("/action", handler.DouyinPublishActionMethod)
	auth2.GET("/list", handler.DouyinPublishListMethod)
	auth3.POST("/action", handler.DouyinFavoriteActionMethod)
	auth3.GET("/list", handler.DouyinFavoriteListMethod)
	auth4.POST("/action", handler.DouyinCommentActionMethod)
	auth4.GET("/list", handler.DouyinCommentListMethod)

}
