// Code generated by hertz generator. DO NOT EDIT.

package routers

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	//router "github.com/41197-yhkt/tiktok/gateway/internal/routers/router"
)

// register registers all routers.
func Register(r *server.Hertz) {

	GeneratedRegister(r)

	customizedRegister(r)
}
