// Code generated by Kitex v0.4.4. DO NOT EDIT.

package douyinservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	video "github.com/41197-yhkt/tiktok-video/kitex_gen/video"
)

func serviceInfo() *kitex.ServiceInfo {
	return douyinServiceServiceInfo
}

var douyinServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "DouyinService"
	handlerType := (*video.DouyinService)(nil)
	methods := map[string]kitex.MethodInfo{
		"DouyinPublishActionMethod": kitex.NewMethodInfo(douyinPublishActionMethodHandler, newDouyinServiceDouyinPublishActionMethodArgs, newDouyinServiceDouyinPublishActionMethodResult, false),
		"DouyinPublishListMethod":   kitex.NewMethodInfo(douyinPublishListMethodHandler, newDouyinServiceDouyinPublishListMethodArgs, newDouyinServiceDouyinPublishListMethodResult, false),
		"DouyinGetVideoMethod":      kitex.NewMethodInfo(douyinGetVideoMethodHandler, newDouyinServiceDouyinGetVideoMethodArgs, newDouyinServiceDouyinGetVideoMethodResult, false),
		"DouyinMGetVideoMethod":     kitex.NewMethodInfo(douyinMGetVideoMethodHandler, newDouyinServiceDouyinMGetVideoMethodArgs, newDouyinServiceDouyinMGetVideoMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func douyinPublishActionMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.DouyinServiceDouyinPublishActionMethodArgs)
	realResult := result.(*video.DouyinServiceDouyinPublishActionMethodResult)
	success, err := handler.(video.DouyinService).DouyinPublishActionMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDouyinServiceDouyinPublishActionMethodArgs() interface{} {
	return video.NewDouyinServiceDouyinPublishActionMethodArgs()
}

func newDouyinServiceDouyinPublishActionMethodResult() interface{} {
	return video.NewDouyinServiceDouyinPublishActionMethodResult()
}

func douyinPublishListMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.DouyinServiceDouyinPublishListMethodArgs)
	realResult := result.(*video.DouyinServiceDouyinPublishListMethodResult)
	success, err := handler.(video.DouyinService).DouyinPublishListMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDouyinServiceDouyinPublishListMethodArgs() interface{} {
	return video.NewDouyinServiceDouyinPublishListMethodArgs()
}

func newDouyinServiceDouyinPublishListMethodResult() interface{} {
	return video.NewDouyinServiceDouyinPublishListMethodResult()
}

func douyinGetVideoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.DouyinServiceDouyinGetVideoMethodArgs)
	realResult := result.(*video.DouyinServiceDouyinGetVideoMethodResult)
	success, err := handler.(video.DouyinService).DouyinGetVideoMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDouyinServiceDouyinGetVideoMethodArgs() interface{} {
	return video.NewDouyinServiceDouyinGetVideoMethodArgs()
}

func newDouyinServiceDouyinGetVideoMethodResult() interface{} {
	return video.NewDouyinServiceDouyinGetVideoMethodResult()
}

func douyinMGetVideoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.DouyinServiceDouyinMGetVideoMethodArgs)
	realResult := result.(*video.DouyinServiceDouyinMGetVideoMethodResult)
	success, err := handler.(video.DouyinService).DouyinMGetVideoMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDouyinServiceDouyinMGetVideoMethodArgs() interface{} {
	return video.NewDouyinServiceDouyinMGetVideoMethodArgs()
}

func newDouyinServiceDouyinMGetVideoMethodResult() interface{} {
	return video.NewDouyinServiceDouyinMGetVideoMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DouyinPublishActionMethod(ctx context.Context, req *video.DouyinPublishActionRequest) (r *video.DouyinPublishActionResponse, err error) {
	var _args video.DouyinServiceDouyinPublishActionMethodArgs
	_args.Req = req
	var _result video.DouyinServiceDouyinPublishActionMethodResult
	if err = p.c.Call(ctx, "DouyinPublishActionMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DouyinPublishListMethod(ctx context.Context, req *video.DouyinPublishListRequest) (r *video.DouyinPublishListResponse, err error) {
	var _args video.DouyinServiceDouyinPublishListMethodArgs
	_args.Req = req
	var _result video.DouyinServiceDouyinPublishListMethodResult
	if err = p.c.Call(ctx, "DouyinPublishListMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DouyinGetVideoMethod(ctx context.Context, req *video.GetVideoRequest) (r *video.GetVideoResponse, err error) {
	var _args video.DouyinServiceDouyinGetVideoMethodArgs
	_args.Req = req
	var _result video.DouyinServiceDouyinGetVideoMethodResult
	if err = p.c.Call(ctx, "DouyinGetVideoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DouyinMGetVideoMethod(ctx context.Context, req *video.MGetVideoRequest) (r *video.MGetVideoResponse, err error) {
	var _args video.DouyinServiceDouyinMGetVideoMethodArgs
	_args.Req = req
	var _result video.DouyinServiceDouyinMGetVideoMethodResult
	if err = p.c.Call(ctx, "DouyinMGetVideoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
