// Code generated by hertz generator.

package Douyin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinfeedmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinusermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyincomment_ctionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyincommentlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinfavorite_ctionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinfavoritelistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinpublish_ctionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinpublishlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinrelation_ctionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinrelationfollowlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinrelationfollowerlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinrelationfriendlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinuserloginmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinuserregistermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
