// Code generated by Kitex v0.4.4. DO NOT EDIT.
package compositeservice

import (
	server "github.com/cloudwego/kitex/server"
	composite "tiktok-gateway/kitex_gen/composite"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler composite.CompositeService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
